# Generated by Django 4.1.7 on 2023-07-27 01:35

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True)),
                ('category_name', models.CharField(max_length=255)),
                ('slug_field', models.SlugField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('is_active', django.db.models.manager.Manager()),
            ],
        ),
    ]
